name: ir-project

services:
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    image: ir-project/api-gateway
    container_name: ir-api-gateway
    env_file:
      - path: .env
        required: true
    ports:
      - "${API_GATEWAY_PORT:-8000}:8000"
    networks:
      - ir-net
    restart: unless-stopped

  preprocessing-service:
    build:
      context: .
      dockerfile: services/preprocessing-service/Dockerfile
    image: ir-project/preprocessing-service
    container_name: ir-preprocessing
    env_file:
      - path: .env
        required: true
    ports:
      - "${PREPROCESSING_PORT:-8001}:8001"
    networks:
      - ir-net
    restart: unless-stopped

networks:
  ir-net:
    driver: bridge
