"""Shared request/response contracts used across all services.

Every cross-service payload is a pydantic model defined here, imported by both
the caller and the callee. No ad-hoc dicts cross a service boundary.
"""

from shared.contracts.common import (
    ErrorDetail,
    ErrorEnvelope,
    HealthResponse,
    ServiceInfo,
)
from shared.contracts.jobs import (
    JobRef,
    JobStatus,
    ref_from_job,
    status_from_job,
)
from shared.contracts.preprocessing import (
    PreprocessBatchRequest,
    PreprocessBatchResponse,
    PreprocessOptions,
    PreprocessRequest,
    PreprocessResult,
)
from shared.contracts.indexing import (
    BuildIndexRequest,
    BuiltIndexes,
    DocInfo,
    IndexDeleteResult,
    IndexStats,
    IndexStatusResponse,
    Posting,
    PostingsResponse,
    TermStats,
)
from shared.contracts.representation import (
    BertBuildParams,
    Bm25BuildParams,
    BuildRepresentationRequest,
    BuiltRepresentation,
    BuiltRepresentations,
    EmbeddingBuildParams,
    EncodeRequest,
    EncodeResponse,
    EncodedVector,
    HybridSpec,
    RepresentationDeleteResult,
    RepresentationStats,
    RepresentationStatusResponse,
    SearchHit,
    SearchRequest,
    SearchResponse,
    TfidfParams,
    WeightedTerm,
)
from shared.contracts.docstore import (
    DatasetInfo,
    DatasetStatus,
    DeleteDatasetRequest,
    DeleteResult,
    DocListItem,
    DocListResponse,
    DocsRequest,
    DocsResponse,
    DownloadDatasetRequest,
    PrepareDatasetRequest,
    RawDoc,
)

__all__ = [
    "ErrorDetail",
    "ErrorEnvelope",
    "HealthResponse",
    "ServiceInfo",
    "JobRef",
    "JobStatus",
    "ref_from_job",
    "status_from_job",
    "PreprocessBatchRequest",
    "PreprocessBatchResponse",
    "PreprocessOptions",
    "PreprocessRequest",
    "PreprocessResult",
    "BuildIndexRequest",
    "BuiltIndexes",
    "DocInfo",
    "IndexDeleteResult",
    "IndexStats",
    "IndexStatusResponse",
    "Posting",
    "PostingsResponse",
    "TermStats",
    "BertBuildParams",
    "Bm25BuildParams",
    "BuildRepresentationRequest",
    "BuiltRepresentation",
    "BuiltRepresentations",
    "EmbeddingBuildParams",
    "EncodeRequest",
    "EncodeResponse",
    "EncodedVector",
    "HybridSpec",
    "RepresentationDeleteResult",
    "RepresentationStats",
    "RepresentationStatusResponse",
    "SearchHit",
    "SearchRequest",
    "SearchResponse",
    "TfidfParams",
    "WeightedTerm",
    "DatasetInfo",
    "DatasetStatus",
    "DeleteDatasetRequest",
    "DeleteResult",
    "DocListItem",
    "DocListResponse",
    "DocsRequest",
    "DocsResponse",
    "DownloadDatasetRequest",
    "PrepareDatasetRequest",
    "RawDoc",
]
